---

- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Add Elasticsearch Signing Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{
              kibana_major_version }}.x/apt stable main"

- name: Install Kibana
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - kibana

- name: Disable automatic updates
  copy:
    content: |
      Unattended-Upgrade::Package-Blacklist {
        "kibana";
      };
    dest: /etc/apt/apt.conf.d/55kibana-disable
  when: kibana_disable_auto_update | bool
