---

- name: Initialize variable
  set_fact:
    kibana_combined_config: {}

- name: Load platform specific variables
  include_vars:
    file: "{{ lookup('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}.yml"
      paths:
        - 'vars'
