---

- name: Combine configs
  set_fact:
    kibana_combined_config: >-
      {{
        _kibana_default_config
        | combine(kibana_combined_config, recursive=True)
        | combine(kibana_config, recursive=True)
      }}

- name: Upload kibana configuration
  copy:
    content: >-
      {{
        kibana_combined_config
        | to_nice_yaml(indent=2, explicit_start=True)
      }}
    dest: /etc/kibana/kibana.yml
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
  notify: kibana restart service

- name: Upload startup overrides
  blockinfile:
    path: "{{ _kibana_startup_env_file }}"
    block: "{{ kibana_startup_overrides }}"
  when: kibana_startup_overrides != None
  notify: kibana restart service
