---

- name: Check if a keystore exists
  stat:
    path: /var/lib/kibana/kibana.keystore
  register: result

- name: Create kibana keystore
  command: /usr/share/kibana/bin/kibana-keystore create
  when: not result.stat.exists | bool
