---

- name: Check if a keystore exists
  stat:
    # TODO not sure how the keystore path is being decided
    path: /etc/kibana/kibana.keystore
  register: result

- name: Create kibana keystore
  command: /usr/share/kibana/bin/kibana-keystore create
  when: not result.stat.exists | bool
  become: true
  become_user: "{{ kibana_user }}"
