---

- name: Check if a keystore exists
  stat:
    path: /var/lib/kibana/kibana.keystore
  register: result

- name: Create kibana keystore
  command: /usr/share/kibana/bin/kibana-keystore create --allow-root
  when: not result.stat.exists | bool
  become: true
  become_user: "{{ kibana_user }}"
