---

- name: Start the kibana service
  systemd:
    name: kibana
    enabled: true
    state: started

- name: Check kibana was started succesfully
  uri:
    url: "http://{{ kibana_host }}:{{ kibana_port }}"
    return_content: true
    validate_certs: true
  register: result
  until: result is success
  retries: 11
  delay: 5
  failed_when:
    - result is failed
