---
- name: Converge
  hosts: all
  roles:
    - role: nkakouros.kibana
  vars:
    # Re-using variables from `molecule/default/prepare.yml` to show how
    # existing information could be re-used if you combined the two playbooks
    # (`prepare.yml` and `playbook.yml` in one).
    elastic_certificates_password: 'nk}$Q%];a3Gy$E!QvT8E'
    elastic_builtin_users_password_backup_file: ~/elk/elastic-passwords
    elastic_certificates_download_dir: ~/elk/certs/
    kibana_host: "{{ ansible_default_ipv4.address }}"
    kibana_elasticsearch_user: >-
      {{
        (
          lookup('file', elastic_builtin_users_password_backup_file)
          | from_yaml
          | selectattr('name', 'equalto', 'kibana')
          | list
        )[0]
      }}
    kibana_elastic_certificates:
      ca: "{{ elastic_certificates_download_dir }}/ca/ca.crt"
      crt: "{{ elastic_certificates_download_dir
              }}/kibana-backend/kibana-backend.crt"
      key: "{{ elastic_certificates_download_dir
              }}/kibana-backend/kibana-backend.key"
    kibana_elastic_certificates_passphrase:
      "{{ elastic_certificates_password }}"
    kibana_config:
      elasticsearch:
        ssl:
          alwaysPresentCertificate: true
