---

- name: Remove existing keystore settings
  command:
    /usr/share/kibana/bin/kibana-keystore remove "{{ item }}"
  register: result
  failed_when:
    - result is failed
    - result.stderr is not search('does not exist in the keystore')
  when: kibana_update_passwords | bool
  loop:
    - elasticsearch.username
    - elasticsearch.ssl.keyPassphrase

- name: List keystore settings
  command: /usr/share/kibana/bin/kibana-keystore list
  register: _kibana_keystore_settings
  changed_when: false

- name: Add certificate password to kibana keystore
  shell: |
    set -o pipefail;
    echo {{ kibana_elastic_certificates_passphrase }} |
      /usr/share/kibana/bin/kibana-keystore --stdin add \
        {{ item }}
  args:
    executable: /bin/bash
  when: _kibana_keystore_settings.stdout is not search(item)
  loop:
    - elasticsearch.ssl.keyPassphrase
  notify: kibana restart service

- name: Add certificate password to kibana keystore
  shell: |
    set -o pipefail;
    echo {{ kibana_user.password }} |
      /usr/share/kibana/bin/kibana-keystore --stdin add \
        --stdin \
        {{ item }}
  args:
    executable: /bin/bash
  when:
    - kibana_user.password is defined
    - _kibana_keystore_settings.stdout is not search(item)
  loop:
    - elasticsearch.username
  notify: kibana restart service
