---

- name: Remove existing keystore settings
  command:
    /usr/share/kibana/bin/kibana-keystore remove "{{ item }}"
  register: result
  failed_when:
    - result is failed
    - result.stderr is not search('does not exist in the keystore')
  when: kibana_update_passwords | bool
  loop:
    - elasticsearch.username
    - elasticsearch.password
    - elasticsearch.ssl.keyPassphrase

- name: List keystore settings
  command: /usr/share/kibana/bin/kibana-keystore list
  register: _kibana_keystore_settings
  changed_when: false

- name: Add certificate password to kibana keystore
  shell: |
    set -o pipefail;
    echo '{{ kibana_elastic_certificates_passphrase }}' |
    /usr/share/kibana/bin/kibana-keystore add \
      {{ item }} --stdin
  args:
    executable: /bin/bash
  when: _kibana_keystore_settings.stdout is not search(item)
  loop:
    - elasticsearch.ssl.keyPassphrase
  notify: kibana restart service
  no_log: true

- name: Add built-in kibana user name to kibana keystore
  shell: |
    set -o pipefail;
    echo '{{ kibana_elasticsearch_user['name'] }}' |
    /usr/share/kibana/bin/kibana-keystore add \
      {{ item }} --stdin
  args:
    executable: /bin/bash
  when:
    - kibana_elasticsearch_user['name'] is defined
    - _kibana_keystore_settings.stdout is not search(item)
  loop:
    - elasticsearch.username
  notify: kibana restart service
  no_log: true

- name: Add built-in kibana user password to kibana keystore
  shell: |
    set -o pipefail;
    echo '{{ kibana_elasticsearch_user['password'] }}' |
    /usr/share/kibana/bin/kibana-keystore add \
      {{ item }} --stdin
  args:
    executable: /bin/bash
  when:
    - kibana_elasticsearch_user['password'] is defined
    - _kibana_keystore_settings.stdout is not search(item)
  loop:
    - elasticsearch.password
  notify: kibana restart service
  no_log: true
